config-version: 2

name: 'stripe_source'
version: '0.4.3'
require-dbt-version: ">=0.20.0"

models:
    stripe_source:
        materialized: table
        +schema: stg_stripe
        tmp:
          materialized: view

vars:
  stripe_source:
    balance_transaction:   "{{ source('stripe', 'balance_transaction') }}"
    card:                  "{{ source('stripe', 'card') }}"
    charge:                "{{ source('stripe', 'charge') }}"
    customer:              "{{ source('stripe', 'customer') }}"
    fee:                   "{{ source('stripe', 'fee') }}"
    invoice:               "{{ source('stripe', 'invoice') }}"
    invoice_line_item:     "{{ source('stripe', 'invoice_line_item') }}"
    payment_intent:        "{{ source('stripe', 'payment_intent') }}"
    payment_method_card:   "{{ source('stripe', 'payment_method_card') }}"
    payment_method:        "{{ source('stripe', 'payment_method') }}"
    payout:                "{{ source('stripe', 'payout') }}"
    plan:                  "{{ source('stripe', 'plan') }}"
    refund:                "{{ source('stripe', 'refund') }}"
    subscription:          "{{ source('stripe', 'subscription') }}"
    credit_note:           "{{ source('stripe', 'credit_note') }}"
    credit_note_line_item: "{{ source('stripe', 'credit_note_line_item') }}"
    
    #Variables to enable or disable models if you do not have the respective table.
    using_invoices:         True
    using_credit_notes:     False
    using_payment_method:   True
    using_subscriptions:    True

    
    # variable to exclude or include test data (based on `livemode`)
    using_livemode: True

    # variable to disable the filter within invoice line item
    using_invoice_line_sub_filter: True
