config-version: 2
name: 'stripe_source'
version: '0.11.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  stripe_source:
    materialized: table
    +schema: stg_stripe
    tmp:
      materialized: view
vars:
  stripe_source:
    account: "{{ source('stripe', 'account') }}"
    balance_transaction: "{{ source('stripe', 'balance_transaction') }}"
    card: "{{ source('stripe', 'card') }}"
    charge: "{{ source('stripe', 'charge') }}"
    credit_note: "{{ source('stripe', 'credit_note') }}"
    credit_note_line_item: "{{ source('stripe', 'credit_note_line_item') }}"
    customer: "{{ source('stripe', 'customer') }}"
    dispute: "{{ source('stripe', 'dispute') }}"
    fee: "{{ source('stripe', 'fee') }}"
    invoice: "{{ source('stripe', 'invoice') }}"
    invoice_line_item: "{{ source('stripe', 'invoice_line_item') }}"
    payment_intent: "{{ source('stripe', 'payment_intent') }}"
    payment_method_card: "{{ source('stripe', 'payment_method_card') }}"
    payment_method: "{{ source('stripe', 'payment_method') }}"
    payout: "{{ source('stripe', 'payout') }}"
    plan: "{{ source('stripe', 'plan') }}"
    price: "{{ source('stripe', 'price') }}"
    refund: "{{ source('stripe', 'refund') }}"
    subscription_history: "{{ source('stripe', 'subscription_history') }}"
    subscription: "{{ source('stripe', 'subscription') }}"
    transfer: "{{ source('stripe', 'transfer') }}"